import { Geist, Geist_Mono, Inter, Montserrat} from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";

import Navbar from "../components/shared/Navbar";
import NavHeader from "../components/shared/NavHeader";
import Footer from "../components/shared/Footer";
import SubscribePopup from "../components/subscribePopup/SubscribePopup";
import BookmarkProvider from "../providers/BookmarkProvider";
import { CategoriesProvider } from "../providers/CategoriesProvider";
import SignupProvider from "../providers/SignupProvider";
import { ThemeProvider } from "../components/themeProvider/theme.provider";
import UserProvider from "../providers/UserProvider";
import PasswordProvider from "../providers/PasswordProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Montserrat font with desired weights
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // You can specify the weights you need
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // You can specify the weights you need
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Maximum Savings App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${inter.variable} antialiased overflow-x-hidden max-w-full`}
      >
        <div className="w-full overflow-x-hidden">
          <ThemeProvider>
            <UserProvider>
              <SignupProvider>
                <CategoriesProvider>
                  <BookmarkProvider>
                    <NavHeader />
                    <Navbar montserrat={montserrat.className}/>
                    <Toaster position="top-center" reverseOrder={false} />
                    <PasswordProvider>
                      <main >
                        {children}
                      </main>
                    </PasswordProvider>
                    {/* <SubscribePopup/> */}
                    <Footer/>
                  </BookmarkProvider>
                </CategoriesProvider>
              </SignupProvider>
            </UserProvider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}