import { Geist, Geist_Mono, Inter, Montserrat} from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";

import Navbar from "../components/shared/Navbar";
import NavHeader from "../components/shared/NavHeader";
import Footer from "../components/shared/Footer";
import SubscribePopup from "../components/subscribePopup/SubscribePopup";
import BookmarkProvider from "../providers/BookmarkProvider";
import { CategoriesProvider } from "../providers/CategoriesProvider";
import SignupProvider from "../providers/SignupProvider";
import { ThemeProvider } from "../components/themeProvider/theme.provider";
import UserProvider from "../providers/UserProvider";
import PasswordProvider from "../providers/PasswordProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Maximum Savings App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var user = localStorage.getItem('user');
                  var accessToken = localStorage.getItem('access_token');
                  var userAuthenticated = (user && user !== 'null' && user !== 'undefined') || (accessToken && accessToken !== 'null');
                  
                  if (!userAuthenticated) {
                    document.documentElement.classList.remove('dark');
                    document.documentElement.style.colorScheme = 'light';
                    localStorage.setItem('theme', 'light');
                  } else {
                    var theme = localStorage.getItem('theme') || 'light';
                    if (theme === 'dark') {
                      document.documentElement.classList.add('dark');
                      document.documentElement.style.colorScheme = 'dark';
                    } else {
                      document.documentElement.classList.remove('dark');
                      document.documentElement.style.colorScheme = 'light';
                    }
                  }
                } catch (e) {
                  document.documentElement.classList.remove('dark');
                  document.documentElement.style.colorScheme = 'light';
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${inter.variable} antialiased`}
      >
          <ThemeProvider>
              <UserProvider>
                 <SignupProvider>
              <CategoriesProvider>
            <BookmarkProvider>
             <NavHeader />
            <Navbar montserrat={montserrat.className}/>
            <Toaster position="top-center" reverseOrder={false} />
            <PasswordProvider>
              {children}
            </PasswordProvider>
            {/* <SubscribePopup/> */}
            <Footer/>
           </BookmarkProvider>
           </CategoriesProvider>
            </SignupProvider>
              </UserProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}